from . import auto_calcul_age
from . import type_contrat
from . import document_management
from . import skill_qualification
from . import matricule
from . import duree_service
from . import poste_categorie
from . import organigramme
from . import multi_poste